// Code generated by MockGen. DO NOT EDIT.
// Source: stvCms/internal/repository (interfaces: IPostRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_post_repository.go -package=mocks stvCms/internal/repository IPostRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "stvCms/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockIPostRepository is a mock of IPostRepository interface.
type MockIPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPostRepositoryMockRecorder
	isgomock struct{}
}

// MockIPostRepositoryMockRecorder is the mock recorder for MockIPostRepository.
type MockIPostRepositoryMockRecorder struct {
	mock *MockIPostRepository
}

// NewMockIPostRepository creates a new mock instance.
func NewMockIPostRepository(ctrl *gomock.Controller) *MockIPostRepository {
	mock := &MockIPostRepository{ctrl: ctrl}
	mock.recorder = &MockIPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPostRepository) EXPECT() *MockIPostRepositoryMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockIPostRepository) CreatePost(post models.Post) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", post)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockIPostRepositoryMockRecorder) CreatePost(post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockIPostRepository)(nil).CreatePost), post)
}

// DeletePostById mocks base method.
func (m *MockIPostRepository) DeletePostById(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostById", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeletePostById indicates an expected call of DeletePostById.
func (mr *MockIPostRepositoryMockRecorder) DeletePostById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostById", reflect.TypeOf((*MockIPostRepository)(nil).DeletePostById), id)
}

// ExistsPost mocks base method.
func (m *MockIPostRepository) ExistsPost(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsPost", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ExistsPost indicates an expected call of ExistsPost.
func (mr *MockIPostRepositoryMockRecorder) ExistsPost(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsPost", reflect.TypeOf((*MockIPostRepository)(nil).ExistsPost), id)
}

// GetPostById mocks base method.
func (m *MockIPostRepository) GetPostById(id uint) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostById", id)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostById indicates an expected call of GetPostById.
func (mr *MockIPostRepositoryMockRecorder) GetPostById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostById", reflect.TypeOf((*MockIPostRepository)(nil).GetPostById), id)
}

// GetPosts mocks base method.
func (m *MockIPostRepository) GetPosts() ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts")
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockIPostRepositoryMockRecorder) GetPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockIPostRepository)(nil).GetPosts))
}

// GetPostsByFilter mocks base method.
func (m *MockIPostRepository) GetPostsByFilter(filter string) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByFilter", filter)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByFilter indicates an expected call of GetPostsByFilter.
func (mr *MockIPostRepositoryMockRecorder) GetPostsByFilter(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByFilter", reflect.TypeOf((*MockIPostRepository)(nil).GetPostsByFilter), filter)
}

// UpdatePost mocks base method.
func (m *MockIPostRepository) UpdatePost(id uint, post models.Post) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", id, post)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockIPostRepositoryMockRecorder) UpdatePost(id, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockIPostRepository)(nil).UpdatePost), id, post)
}
