// Code generated by MockGen. DO NOT EDIT.
// Source: stvCms/internal/repository (interfaces: INotificationRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_notification_repository.go -package=mocks stvCms/internal/repository INotificationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "stvCms/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockINotificationRepository is a mock of INotificationRepository interface.
type MockINotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockINotificationRepositoryMockRecorder is the mock recorder for MockINotificationRepository.
type MockINotificationRepositoryMockRecorder struct {
	mock *MockINotificationRepository
}

// NewMockINotificationRepository creates a new mock instance.
func NewMockINotificationRepository(ctrl *gomock.Controller) *MockINotificationRepository {
	mock := &MockINotificationRepository{ctrl: ctrl}
	mock.recorder = &MockINotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotificationRepository) EXPECT() *MockINotificationRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockINotificationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockINotificationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockINotificationRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockINotificationRepository) GetAll(ctx context.Context) ([]models.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockINotificationRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockINotificationRepository)(nil).GetAll), ctx)
}

// GetUnreadCount mocks base method.
func (m *MockINotificationRepository) GetUnreadCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCount indicates an expected call of GetUnreadCount.
func (mr *MockINotificationRepositoryMockRecorder) GetUnreadCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCount", reflect.TypeOf((*MockINotificationRepository)(nil).GetUnreadCount), ctx)
}

// MarkAllRead mocks base method.
func (m *MockINotificationRepository) MarkAllRead(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockINotificationRepositoryMockRecorder) MarkAllRead(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockINotificationRepository)(nil).MarkAllRead), ctx)
}

// MarkRead mocks base method.
func (m *MockINotificationRepository) MarkRead(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockINotificationRepositoryMockRecorder) MarkRead(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockINotificationRepository)(nil).MarkRead), ctx, id)
}

// Save mocks base method.
func (m *MockINotificationRepository) Save(ctx context.Context, notification models.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockINotificationRepositoryMockRecorder) Save(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockINotificationRepository)(nil).Save), ctx, notification)
}
