// Code generated by MockGen. DO NOT EDIT.
// Source: stvCms/internal/clients (interfaces: IOpenRouterClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_openrouter_client.go -package=mocks stvCms/internal/clients IOpenRouterClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOpenRouterClient is a mock of IOpenRouterClient interface.
type MockIOpenRouterClient struct {
	ctrl     *gomock.Controller
	recorder *MockIOpenRouterClientMockRecorder
	isgomock struct{}
}

// MockIOpenRouterClientMockRecorder is the mock recorder for MockIOpenRouterClient.
type MockIOpenRouterClientMockRecorder struct {
	mock *MockIOpenRouterClient
}

// NewMockIOpenRouterClient creates a new mock instance.
func NewMockIOpenRouterClient(ctrl *gomock.Controller) *MockIOpenRouterClient {
	mock := &MockIOpenRouterClient{ctrl: ctrl}
	mock.recorder = &MockIOpenRouterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOpenRouterClient) EXPECT() *MockIOpenRouterClientMockRecorder {
	return m.recorder
}

// GenAI mocks base method.
func (m *MockIOpenRouterClient) GenAI(text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenAI", text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenAI indicates an expected call of GenAI.
func (mr *MockIOpenRouterClientMockRecorder) GenAI(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenAI", reflect.TypeOf((*MockIOpenRouterClient)(nil).GenAI), text)
}
