// Code generated by MockGen. DO NOT EDIT.
// Source: stvCms/internal/clients (interfaces: IR2Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_r2_client.go -package=mocks stvCms/internal/clients IR2Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockIR2Client is a mock of IR2Client interface.
type MockIR2Client struct {
	ctrl     *gomock.Controller
	recorder *MockIR2ClientMockRecorder
	isgomock struct{}
}

// MockIR2ClientMockRecorder is the mock recorder for MockIR2Client.
type MockIR2ClientMockRecorder struct {
	mock *MockIR2Client
}

// NewMockIR2Client creates a new mock instance.
func NewMockIR2Client(ctrl *gomock.Controller) *MockIR2Client {
	mock := &MockIR2Client{ctrl: ctrl}
	mock.recorder = &MockIR2ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIR2Client) EXPECT() *MockIR2ClientMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockIR2Client) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockIR2ClientMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockIR2Client)(nil).GetObject), varargs...)
}

// PutObject mocks base method.
func (m *MockIR2Client) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockIR2ClientMockRecorder) PutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockIR2Client)(nil).PutObject), varargs...)
}
